### ISSUE TITLE
Cockroachdb fails to init with argocd

### ISSUE THREAD

**Issue by fredleger** [cockroachdb/helm-charts#149]
Hi folks,

I guess we hit an issue quite similar to #69 with argocd

With argocd helm hooks are converted automatically to argocd hooks.
The init job does include annotations with `post-install` and `post-upgrade` stages. They will be converted in `postSync` in argocd (source: https://argoproj.github.io/argo-cd/user-guide/helm/#helm-hooks).

In fact the job will never been triggered because the sync stage will never be over untill all pods are `healthy` which can't occurs without init. inifinite loop :-)

One easy way to fix that is to allow customization of Job annotations (`Job.spec.annotations` not `Job.spec.template.annotations` which are already supported with `init.annotations`). This will allow to add an annotation for Argocd like `argocd.argoproj.io/hook: Sync` which i guess could do the job.

**Comment by fredleger** [comment]
I can confirm than injecting the job with the abvove annotations initialize the cluster as expected

**Comment by wodka** [comment]
would be really nice to add this to the general readme!

```
init:
  jobAnnotations:
    argocd.argoproj.io/hook: Sync
```
