### ISSUE TITLE
Build a final build of cert-manager utility

### ISSUE THREAD

**Issue by prafull01** [cockroachdb/helm-charts#153]
Build the final build of cert manager utility and push it with tag which can act as default tag for the value.yaml.

This way  helm installation should not fail with default `value.yaml` file.

**Comment by udnay** [comment]
Is this done?

**Comment by prafull01** [comment]
Yes, it is automatically done by our CI when we merged the `cert-manager-feature-branch` with the master.

This is the build job run, you can check [here](https://github.com/cockroachdb/helm-charts/runs/3498202465?check_suite_focus=true)
