### ISSUE TITLE
Self-signer container image can't be pulled

### ISSUE THREAD

**Issue by JorritSalverda** [cockroachdb/helm-charts#174]
Currently I'm seeing the following issue when trying to pull image `gcr.io/cockroachlabs-helm-charts/cockroach-self-signer-cert:1.0`.

```
NAME                                    READY   STATUS             RESTARTS   AGE
pod/cockroachdb-self-signer-5ppvc   0/1     ImagePullBackOff   0          10m
```

Trying to pull it locally also results in an error:

```
$ docker pull gcr.io/cockroachlabs-helm-charts/cockroach-self-signer-cert:1.0

1.0: Pulling from cockroachlabs-helm-charts/cockroach-self-signer-cert
785fa0a7e8d6: Pulling fs layer
ab936a5fd3c6: Pulling fs layer
5526c82c0a9b: Pulling fs layer
5e5e7de8552b: Waiting
error pulling image configuration: unknown blob
```

When checking it at https://console.cloud.google.com/gcr/images/cockroachlabs-helm-charts/GLOBAL/cockroach-self-signer-cert there's no mention of any kind of error, but somehow the image seems corrupted.

**Comment by JorritSalverda** [comment]
It seems it's pulling the image again, so might have been an issue on Google's end. Closing this as it's no longer an issue.

**Comment by udnay** [comment]
There was an issue where the image was deleted from the container registry, thank you for flagging it.
