### ISSUE TITLE
Helm chart 6.2.0 doesn't support insecure cluster

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/helm-charts#185]
The default installation of https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/values.yaml has been modified to install a secure cluster instead of insecure (which was the default until version 6.0.9).

If explicitly installing insecure cluster by running:

```
helm install my-release cockroachdb/cockroachdb --set tls.enabled=false
the installation fails, because of 'serviceaccount 'my-release-cockroachdb-self-signer" not found' by self-signer job.
```

The behaviour contradicts the information in the README (https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/README.md).

**Comment by udnay** [comment]
@abhishekdwivedi3060 @prafull01 can you take a look at this? I assume it is due to a misconfiguration?
