### ISSUE TITLE
new config for cert-manager fails

### ISSUE THREAD

**Issue by vincentserpoul** [cockroachdb/helm-charts#235]
using cert-manager 1.7.2

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Certificate.spec.issuerRef): unknown field "clientCertDuration" in io.cert-manager.v1.Certificate.spec.issuerRef, ValidationError(Certificate.spec.issuerRef): unknown field "clientCertExpiryWindow" in io.cert-manager.v1.Certificate.spec.issuerRef, ValidationError(Certificate.spec.issuerRef): unknown field "nodeCertDuration" in io.cert-manager.v1.Certificate.spec.issuerRef, ValidationError(Certificate.spec.issuerRef): unknown field "nodeCertExpiryWindow" in io.cert-manager.v1.Certificate.spec.issuerRef]`

linked to the related commit https://github.com/cockroachdb/helm-charts/commit/d5759b0b4b833951835f06bd9a2dc9dcffa4cd21

**Comment by vincentserpoul** [comment]
@meridional

**Comment by julburg** [comment]
The values in tls.certs.certManagerIssuer are also used for the issuerRef field. Sry my fault that I didn't see that! I will fix it.

**Comment by julburg** [comment]
Here's the PR: https://github.com/cockroachdb/helm-charts/pull/236
Please have a look

**Comment by vincentserpoul** [comment]
7.0.1 pulled today works!
