### ISSUE TITLE
Error "Unable to create ClusterRole" if two releases with same releasename in different namespaces

### ISSUE THREAD

**Issue by amakarov70** [cockroachdb/helm-charts#283]
I insatll two releases with same releasename "cockroachdb" in two namespace "cockroachdb" and "cockroachdb2"
After second helm install:
_Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "cockroachdb" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "cockroachdb2": current value is "cockroachdb"_

In chart ClusterRole have namespace and differen namespaces, but ClusterRole is a cluster-level and not belong to namespace.
Maybe need change name to: **{{ template "cockroachdb.fullname" . }}-{{.Release.NameSpace}}**

**Comment by prafull01** [comment]
Fixed by #301
