### ISSUE TITLE
gcr.io images migration

### ISSUE THREAD

**Issue by NoSugarCoffee** [cockroachdb/helm-charts#440]
The Container Registry is deprecated and scheduled for shutdown on March 18, 2025.
Is there any plan to migrate the image? such as `gcr.io/cockroachlabs-helm-charts/cockroach-self-signer-cert`

**Comment by rail** [comment]
We will be migrating this repo soon, probably without affecting the URL.

**Comment by NoSugarCoffee** [comment]
@rail cool! thanks, man

**Comment by rail** [comment]
This is done now. The underlying repo is backed by Google Artifact registry and all gcr.io requests are redirected to the new location. In other words, there is no need to change the image URLs.
