### ISSUE TITLE
Bug: Helm Chart Secure Clusters will Break with K8s 1.22 Deprecating Our Usage of CSRs

### ISSUE THREAD

**Issue by johnrk-zz** [cockroachdb/helm-charts#52]
In 1.22, Kubernetes is deprecating its suppport of certificate signing requests. This will break how Helm Charts creates secure clusters.

@keith-mcclellan , can you help me find the official deprecation notice from K8s on this?

**Comment by keith-mcclellan** [comment]
It'll be in one of these, probably 1.17 or 1.18 - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#certificatesigningrequest-v1beta1-certificates-k8s-io the feature uses the v1beta1 API which is going away in 1.22 and the v1 api doesn't include it

**Comment by prafull01** [comment]
Implemented as a part of `Certificate Management Feature`. Closing it as complete
