### ISSUE TITLE
copy-certs init container not created when using cert-manager

### ISSUE THREAD

**Issue by mtneug** [cockroachdb/helm-charts#78]
I would expect when using `cert-manager` that setting `tls.certs.certManager` is enough. However, the `copy-certs` init container is not created since `tls.certs.provided` has to be `true` as well. Is this intended? If yes, the documentation should explicitly state that.

**Comment by alleny87** [comment]
This can be solved  by the following pull request.
https://github.com/cockroachdb/helm-charts/pull/253
The copy-certs init container does not run, but that's because the chart is written to have the cert mounted in, just as any other provided certs, but in this case it's cert manager.

**Comment by prafull01** [comment]
Fixed as part of #147  Closing this.
